### ISSUE TITLE
refindit down

### ISSUE THREAD

**Issue by tcatapano** [pensoft/refindit#2]
getting a 503/service unavailable message

**Comment by Biserkov** [comment]
Hi Terry, thanks for the heads-up. Teodor will check this tomorrow.

In the meantime, you can use https://aqueous-shelf-9315.herokuapp.com/

There are some issues with mixed content that I will try to resolve promptly.

**Comment by Biserkov** [comment]
Hi Terry, please let me know if you experience any problems with the aqueous-shelf ;-)

**Comment by tcatapano** [comment]
Thanks for responding so quickly. Much appreciated.

I'm getting results from the basic search, but the advanced search does not
seem to be working. E.g., this query should yield two CrossRef results but
does not:


https://aqueous-shelf-9315.herokuapp.com/find?search=advanced&author=Wheeler&year=1927&origin=Psyche

Thanks/T

**Comment by Biserkov** [comment]
Hi Terry, 

here is why: aqueous-shelf is part of my work on making a one-click installation for ReFindit.

In the default configuration, all databases that require an API-key are disabled until the admin of the instance obtains API-keys and puts them in the configuration file.

If I remember correctly, the API behind CrossRef advanced requires a membership key, while those behind BHL and Mendeley only require registration.

The default install therefore has crossref, datacite, pubmed and gnub for the simple search and datacite and pubmed for the advanced search. The banners are hardcoded in the client, that's why this is not immediately obvious.

**Comment by Biserkov** [comment]
Hi Terry,

the main [ReFindit](http://refindit.org/) is back up.
